server:
  port: 8762

spring:
  application:
    name: GATEWAY-SERVICE


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_NAME:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true