server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_NAME:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true