server:
  port: 8082

spring:
  application:
    name: BILLING-SERVICE
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:billing-db

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_NAME:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true







